#!/usr/bin/env python2

from gnuradio.grc.python.Platform  import Platform

def compile_one(file_name, output_dir):
    platform  = Platform()
    state     = platform.parse_flow_graph(file_name)
    flowgraph = platform.get_new_flow_graph()

    flowgraph.import_data(state)
    flowgraph.validate();

    generator = platform.get_generator()( flowgraph, output_dir )

    generator.write()


import sys,os

output_dir = "~/.grc_gnuradio/"

if "GRC_OUTPUT_DIRECTORY" in os.environ:
    output_dir = os.environ["GRC_OUTPUT_DIRECTORY"]

#print "\n\n\n"
for x in sys.argv[1:]:
    print "compiling %s -> %s \n" % (x, output_dir)
    compile_one(x, output_dir)
